index:
	python index.py -i ../../data/dataset.csv -d entire_dic.txt -p entire_post.txt
search:
	python search.py -d entire_dic.txt -p entire_post.txt -q ../../queries/q1.txt -o ../../queries/r1.txt
	python search.py -d entire_dic.txt -p entire_post.txt -q ../../queries/q2.txt -o ../../queries/r2.txt
	python search.py -d entire_dic.txt -p entire_post.txt -q ../../queries/q3.txt -o ../../queries/r3.txt